name: 'publish'

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v3'

      - name: 'grab tag'
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: 'publish release'
        uses: 'actions/github-script@v6'
        with:
          script: |
            const { readFile } = require('node:fs/promises')
              
            let changelog = await readFile('./changelog.md', { encoding: 'utf-8' })
              
            const startIndex = changelog.indexOf(`## [${process.env.TAG}]`) + `## [${process.env.TAG}](https://github.com/azurystudio/cheetah/releases/tag/${process.env.TAG})\n\n`.length

            changelog = changelog.substring(startIndex)

            const endIndex = changelog.indexOf('\n\n## [')

            changelog = changelog.substring(0, endIndex < 0 ? undefined : endIndex)

            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.TAG,
              name: process.env.TAG,
              body: changelog,
              draft: false,
              prerelease: false
            })
